runtime: python310
env: standard
entrypoint: gunicorn -b :$PORT store.wsgi:application
instance_class: F2

handlers:
  - url: /static
    static_dir: collectstatic
  - url: /.*
    script: auto

runtime_config:
  python_version: 3

automatic_scaling:
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 3
  min_pending_latency: 10ms
  max_pending_latency: 100ms
  max_concurrent_requests: 5
